#!/bin/sh
# nrr - Find Remote Repo - Utility to look up an existing remote repo.
#
# This file is part of nrr-frr, client scripts for newrepo/findrepo.
#
# Written in 2019 by Eliah Kagan <degeneracypressure@gmail.com>.
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

set -ef
server="$(cat ~/.nrr-frr-server)"
test -n "$server"

name="$(basename "$0")"
test -n "$name"

frontend_v="FINDREPO_REMOTE_FRONTEND_COMMAND_NAME=$name"
exec "${GIT_SSH:-ssh}" "$server" env "$frontend_v" findrepo "$@"
