#!/bin/sh
# nrr - Find Remote Repo - Utility to look up an existing remote repo.

set -ef
server="$(cat ~/.nrr-frr-server)"
test -n "$server"

name="$(basename "$0")"
test -n "$name"

frontend_v="FINDREPO_REMOTE_FRONTEND_COMMAND_NAME=$name"
debug_v='DEBUG_COSINE_SIMILARITY='
exec "${GIT_SSH:-ssh}" "$server" env "$frontend_v" "$debug_v" findrepo "$@"
