#!/bin/sh
# nrr - New Remote Repo - Utility to create a new remote repo.
#
# This file is part of nrr-frr, client scripts for newrepo/findrepo.
#
# Written in 2019 by Eliah Kagan <degeneracypressure@gmail.com>.
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

set -ef
server="$(cat ~/.nrr-frr-server)"
test -n "$server"

exec "${GIT_SSH:-ssh}" "$server" newrepo "$@"
